name       : perl-libintl
version    : '1.33'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/G/GU/GUIDO/libintl-perl-1.33.tar.gz : 5126eda9ccd0eeb10db82ddef63cbcaf7dbd771e78cc0fb110cc3b5a6b8679e7
homepage   : https://metacpan.org/pod/Locale::Util
license    : GPL-3.0-or-later
component  : programming.perl
summary    : Internationalization (gettext API) for Perl
description: |
    The package libintl-perl is an internationalization library for Perl that aims to be compatible with the Uniforum message translations system as implemented for example in GNU gettext.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
