name       : perl-libintl
version    : 1.26
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/G/GU/GUIDO/libintl-perl-1.26.tar.gz : 3f28eaa9d824c2852cf96bb6aa98495d302a6b95302f3e0738fe9389f8053e50
license    : GPL-3.0
component  : programming.perl
summary    : Internationalization (gettext API) for Perl
description: |
    The package libintl-perl is an internationalization library for Perl
    that aims to be compatible with the Uniforum message translations
    system as implemented for example in GNU gettext.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
